name: Prettier Fixer

on:
  pull_request:
    branches:
      - "**"

jobs:
  prettier-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run Prettier and fix issues
        run: prettier -w

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B prettier-fix-branch
          git add .
          git commit -m "Prettier fixes"
          git push -u origin prettier-fix-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: prettier-fix-branch
          base: ${{ github.head_ref }}
          title: "prettier fixes"
          body: "This PR merges Prettier fixes back to the original branch"
