name: Prettier Fixer

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "**"

jobs:
  prettier-fix:
    runs-on: ubuntu-latest
    env:
      fixBranch: ${{ github.head_ref }}-prettier-fix

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Install prettier
        run: npm install -G prettier

      - name: Run Prettier and fix issues
        run: npm run format

      - name: Commit and push changes
        run: |
          echo "Setting Git Variables"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          echo "Checking out a new branch: ${{ env.fixBranch }}"
          git checkout -B ${{ env.fixBranch }}
          echo "Status:"
          git status
          echo "---------------------"
          echo "Adding changes"
          git add .
          echo "Committing changes"
          git commit -m "Prettier fixes"
          echo "Pushing changes"
          git push -u origin ${{ env.fixBranch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.fixBranch }}


      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.fixBranch }}
          base: ${{ github.head_ref }}
          title: "prettier fixes"
          body: "This PR merges Prettier fixes back to the original branch"
